# spring.application.name=Java-Project
# # Database URL
# spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name

# # Database credentials
# spring.datasource.username=your_database_username
# spring.datasource.password=your_database_password

# # Specify the MySQL driver
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # Hibernate properties
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # Optional: Configure Hibernate dialect for MySQL
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server:
  port: 9192

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/booking_app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
